name: splatpose
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit-dev
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - tqdm
  - glm=0.9.9.8
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
